export { buildConstraintDerivation, formatConstraint, formatConstraintNumber } from "./constraintDerivation";
export { classifyRegion, findFeasiblePoint, findStrictFeasiblePoint } from "./feasibleRegion";
export { verticesFromLines } from "./halfPlaneIntersection";
export { isObjectiveDirectionUnbounded } from "./objectiveDirection";
export type { BoundaryRay } from "./openRegionBoundary";
export { buildOpenBoundaryRays, hasOpenBoundaryClosure } from "./openRegionBoundary";
export { hasPolytopeLines, hasPolytopeVertices } from "./polytopeTypes";
export type { PolytopeRepresentation } from "./polytopeTypes";
export { VRep, centroid, isConvexChain } from "./polygon";
export { deriveRegionFromPoints } from "./regionAssembly";
